Repository Donation-Project/backend, pull requests merged in 2022-10, with the labels that each got.

#1 feat: 유저 CRUD 추가
  .gitignore
  build.gradle
  src/docs/asciidoc/index.adoc
  src/main/java/com/donation/DonationApplication.java
  src/main/java/com/donation/common/CommonResponse.java
  src/main/java/com/donation/common/ErrorResponse.java
  src/main/java/com/donation/common/reponse/user/UserRespDto.java
  src/main/java/com/donation/common/request/user/UserJoinReqDto.java
  src/main/java/com/donation/common/request/user/UserLoginReqDto.java
  src/main/java/com/donation/config/ConstConfig.java
  src/main/java/com/donation/config/JpaConfig.java
  src/main/java/com/donation/config/S3Config.java
  src/main/java/com/donation/config/WebSecurityConfig.java
  src/main/java/com/donation/config/auth/oauth/GoogleUserInfo.java
  src/main/java/com/donation/config/auth/oauth/OAuth2UserInfo.java
  src/main/java/com/donation/config/auth/oauth/PrincipalDetails.java
  src/main/java/com/donation/config/auth/oauth/PrincipalDetailsService.java
  src/main/java/com/donation/config/auth/oauth/PrincipalOAuth2UserService.java
  src/main/java/com/donation/config/auth/token/TokenProvider.java
  src/main/java/com/donation/config/auth/token/TokenProviderService.java
  src/main/java/com/donation/config/security/SecurityConfig.java
  src/main/java/com/donation/config/security/WebMvcConfig.java
  src/main/java/com/donation/domain/entites/User.java
  src/main/java/com/donation/domain/enums/Role.java
  src/main/java/com/donation/exception/HighestLevelException.java
  src/main/java/com/donation/exception/NoSuchElementException.java
  src/main/java/com/donation/exception/s3/EmptyFileException.java
  src/main/java/com/donation/exception/s3/FileUploadFailedException.java
  src/main/java/com/donation/exception/user/EmailDuplicateException.java
  src/main/java/com/donation/repository/user/UserCustomRepository.java
  src/main/java/com/donation/repository/user/UserCustomRepositoryImpl.java
  src/main/java/com/donation/repository/user/UserRepository.java
  src/main/java/com/donation/service/s3/AwsS3Service.java
  src/main/java/com/donation/service/user/UserService.java
  src/main/java/com/donation/web/controller/ApiSpecController.java
  src/main/java/com/donation/web/controller/user/UserController.java
  src/main/java/com/donation/web/handler/UserControllerExceptionHandler.java
  src/main/resources/application.yml
  src/main/resources/template/docs/index.html
  src/main/resources/templates/docs/index.html
  src/test/java/com/donation/controller/user/UserControllerDocTest.java
  src/test/java/com/donation/controller/user/UserControllerTest.java
  src/test/java/com/donation/repository/user/UserRepositoryTest.java
  src/test/java/com/donation/service/user/UserServiceTest.java
Labels: 백엔드

#3 POST feature - 테스트 코드 작성, API 문서화
  src/docs/asciidoc/index.adoc
  src/main/java/com/donation/common/request/post/PostSaveReqDto.java
  src/main/java/com/donation/common/request/post/PostUpdateReqDto.java
  src/main/java/com/donation/common/request/user/UserJoinReqDto.java
  src/main/java/com/donation/repository/post/PostRepositoryCustom.java
  src/main/java/com/donation/repository/post/PostRepositoryCustomImpl.java
  src/main/java/com/donation/service/post/PostService.java
  src/main/java/com/donation/service/s3/AwsS3Service.java
  src/main/java/com/donation/web/controller/mypage/MyPageController.java
  src/main/java/com/donation/web/controller/post/PostController.java
  src/main/java/com/donation/web/handler/PostControllerExceptionHandler.java
  src/main/resources/templates/docs/index.html
  src/test/java/com/donation/controller/post/PostControllerDocTest.java
  src/test/java/com/donation/controller/post/PostControllerTest.java
  src/test/java/com/donation/controller/user/UserControllerDocTest.java
  src/test/java/com/donation/controller/user/UserControllerTest.java
  src/test/java/com/donation/service/post/PostServiceTest.java
Labels: 백엔드, 리팩터링

#5 Merge 관리자 리스트 조회 ,대기글 수락삭제 기능
  src/main/java/com/donation/domain/entites/Post.java
  src/main/java/com/donation/repository/post/PostRepositoryCustom.java
  src/main/java/com/donation/repository/post/PostRepositoryCustomImpl.java
  src/main/java/com/donation/service/post/PostService.java
  src/main/java/com/donation/web/controller/Admin/AdminController.java
  src/test/java/com/donation/controller/admin/AdminControllerDocTest.java
  src/test/java/com/donation/controller/admin/AdminControllerTest.java
Labels: 백엔드

#6 feat : 포스팅 이미지 업로드 추가
  src/main/java/com/donation/common/response/post/PostFindRespDto.java
  src/main/java/com/donation/common/response/post/PostSaveRespDto.java
  src/main/java/com/donation/domain/entites/Post.java
  src/main/java/com/donation/domain/entites/PostDetailImage.java
  src/main/java/com/donation/repository/post/PostRepositoryCustomImpl.java
  src/main/java/com/donation/repository/postdetailimage/PostDetailImageRepository.java
  src/main/java/com/donation/service/post/PostService.java
  src/main/java/com/donation/service/s3/AwsS3Service.java
  src/main/java/com/donation/service/user/UserService.java
  src/main/java/com/donation/web/controller/post/PostController.java
  src/main/java/com/donation/web/controller/user/UserController.java
  src/main/resources/templates/docs/index.html
  src/test/java/com/donation/controller/post/PostControllerDocTest.java
  src/test/java/com/donation/controller/post/PostControllerTest.java
  src/test/java/com/donation/service/post/PostServiceTest.java
Labels: bug, 백엔드, 리팩터링

#8 feat : 포스팅 좋아요 기능 추가
  build.gradle
  src/docs/asciidoc/index.adoc
  src/main/java/com/donation/common/response/post/PostFindRespDto.java
  src/main/java/com/donation/config/RedisConfig.java
  src/main/java/com/donation/domain/entites/Favorites.java
  src/main/java/com/donation/domain/entites/PostDetailImage.java
  src/main/java/com/donation/repository/favorite/FavoriteRedisRepository.java
  src/main/java/com/donation/repository/favorite/FavoriteRepository.java
  src/main/java/com/donation/repository/user/UserRepository.java
  src/main/java/com/donation/service/favorite/FavoriteService.java
  src/main/java/com/donation/service/post/PostService.java
  src/main/java/com/donation/service/user/UserService.java
  src/main/java/com/donation/web/controller/favortie/FavoriteController.java
  src/main/java/com/donation/web/controller/user/UserController.java
  src/main/java/com/donation/web/handler/GlobalControllerExceptionHandler.java
  src/main/java/com/donation/web/handler/UserControllerExceptionHandler.java
  src/main/resources/templates/docs/index.html
  src/test/java/com/donation/controller/favorite/FavoriteControllerDocTest.java
  src/test/java/com/donation/controller/favorite/FavoriteControllerTest.java
  src/test/java/com/donation/controller/user/UserControllerDocTest.java
  src/test/java/com/donation/controller/user/UserControllerTest.java
  src/test/java/com/donation/repository/favorite/FavoriteRepositoryTest.java
  src/test/java/com/donation/service/favorite/FavoriteServiceTest.java
  src/test/java/com/donation/service/user/UserServiceTest.java
Labels: 백엔드, 리팩터링, feat

#13 fix: 포스트 이미지 저장 방식 변경
  src/main/java/com/donation/common/request/post/PostSaveReqDto.java
  src/main/java/com/donation/service/post/PostService.java
  src/main/java/com/donation/service/s3/AwsS3Service.java
  src/main/java/com/donation/web/controller/post/PostController.java
  src/main/resources/templates/docs/index.html
  src/test/java/com/donation/controller/post/PostControllerDocTest.java
  src/test/java/com/donation/controller/post/PostControllerTest.java
  src/test/java/com/donation/service/post/PostServiceTest.java
Labels: 백엔드, 리팩터링, fix

#15 feat: Jacoco 설정 추가
  build.gradle
  lombok.config
  src/main/resources/templates/docs/index.html
  src/test/java/com/donation/controller/favorite/FavoriteControllerDocTest.java
  src/test/java/com/donation/controller/favorite/FavoriteControllerTest.java
  src/test/java/com/donation/controller/post/PostControllerDocTest.java
  src/test/java/com/donation/controller/post/PostControllerTest.java
  src/test/java/com/donation/repository/favorite/FavoriteRepositoryTest.java
  src/test/java/com/donation/service/favorite/FavoriteServiceTest.java
  src/test/java/com/donation/service/post/PostServiceTest.java
Labels: 백엔드, feat

#20 refactor: RDS 설정에 따른 Profile 설정
  .github/workflows/gradle.yml
  .gitignore
  Dockerfile
  src/main/java/com/donation/domain/entites/Answer.java
  src/main/java/com/donation/domain/entites/Donation.java
  src/main/java/com/donation/domain/entites/Favorites.java
  src/main/java/com/donation/domain/entites/Inquiry.java
  src/main/java/com/donation/domain/entites/Post.java
  src/main/java/com/donation/domain/entites/PostDetailImage.java
  src/main/java/com/donation/domain/entites/Reviews.java
  src/main/resources/application-local.yml
  src/main/resources/application.yml
  src/main/resources/db/migration/V001__init.sql
  src/main/resources/templates/docs/index.html
Labels: 백엔드, 리팩터링, fix

#22 fix: Amount float형에서 String 형으로 변환
  src/main/java/com/donation/common/request/donation/DonationSaveReqDto.java
  src/main/java/com/donation/common/request/post/PostSaveReqDto.java
  src/main/java/com/donation/common/request/post/PostUpdateReqDto.java
  src/main/java/com/donation/common/response/donation/DonationFindByFilterRespDto.java
  src/main/java/com/donation/common/response/donation/DonationFindRespDto.java
  src/main/java/com/donation/common/response/post/PostFindRespDto.java
  src/main/java/com/donation/common/response/post/PostListRespDto.java
  src/main/java/com/donation/common/response/post/PostSaveRespDto.java
  src/main/java/com/donation/domain/entites/Donation.java
  src/main/java/com/donation/domain/entites/Post.java
  src/main/java/com/donation/repository/donation/DonationRepositoryCustomImpl.java
  src/main/java/com/donation/service/donation/DonationService.java
  src/main/resources/db/migration/V002__amount_float_to_String.sql
  src/test/java/com/donation/controller/donation/DonationControllerDocTest.java
  src/test/java/com/donation/controller/donation/DonationControllerTest.java
  src/test/java/com/donation/service/donation/DonationServiceTest.java
  src/test/java/com/donation/testutil/TestDtoDataFactory.java
  src/test/java/com/donation/testutil/TestEntityDataFactory.java
Labels: 백엔드, 리팩터링, Merge, fix

#24 refactor: refactor: 프로그램 전체 리팩토링 Post
  src/main/java/com/donation/common/request/post/PostSaveReqDto.java
  src/main/java/com/donation/common/request/post/PostUpdateReqDto.java
  src/main/java/com/donation/common/response/post/PostFindRespDto.java
  src/main/java/com/donation/common/response/post/PostListRespDto.java
  src/main/java/com/donation/common/response/post/PostSaveRespDto.java
  src/main/java/com/donation/common/response/user/UserRespDto.java
  src/main/java/com/donation/domain/embed/Write.java
  src/main/java/com/donation/domain/entites/Favorites.java
  src/main/java/com/donation/domain/entites/Post.java
  src/main/java/com/donation/domain/enums/Category.java
  src/main/java/com/donation/repository/post/PostRepository.java
  src/main/java/com/donation/repository/post/PostRepositoryCustom.java
  src/main/java/com/donation/repository/post/PostRepositoryCustomImpl.java
  src/main/java/com/donation/repository/postdetailimage/PostDetailImageRepository.java
  src/main/java/com/donation/repository/user/UserRepository.java
  src/main/java/com/donation/service/donation/DonationService.java
  src/main/java/com/donation/service/favorite/FavoriteService.java
  src/main/java/com/donation/service/post/PostScheduleService.java
  src/main/java/com/donation/service/post/PostService.java
  src/main/java/com/donation/service/user/UserService.java
  src/main/java/com/donation/web/controller/admin/AdminController.java
  src/main/java/com/donation/web/controller/post/PostController.java
  src/main/resources/application-local.yml
  src/main/resources/templates/docs/index.html
  src/test/java/com/donation/common/PostFixtures.java
  src/test/java/com/donation/controller/post/PostControllerDocTest.java
  src/test/java/com/donation/controller/post/PostControllerTest.java
  src/test/java/com/donation/domain/PostTest.java
  src/test/java/com/donation/domain/UserTest.java
  src/test/java/com/donation/repository/post/PostRepositoryTest.java
  src/test/java/com/donation/service/post/PostScheduleServiceTest.java
  src/test/java/com/donation/service/post/PostServiceTest.java
  src/test/resources/application.yml
Labels: 백엔드, 리팩터링

#25 refactor: 프로그램 전체 리팩토링 Favorite
  build.gradle
  src/docs/asciidoc/index.adoc
  src/main/java/com/donation/common/request/favorites/LikeSaveAndCancelReqDto.java
  src/main/java/com/donation/config/RedisConfig.java
  src/main/java/com/donation/domain/entites/Favorites.java
  src/main/java/com/donation/repository/favorite/FavoriteRedisRepository.java
  src/main/java/com/donation/repository/favorite/FavoriteRepository.java
  src/main/java/com/donation/service/favorite/FavoriteService.java
  src/main/java/com/donation/web/controller/favortie/FavoriteController.java
  src/main/resources/templates/docs/index.html
  src/test/java/com/donation/common/FavoriteFixtures.java
  src/test/java/com/donation/common/TestDtoDataFactory.java
  src/test/java/com/donation/common/TestEntityDataFactory.java
  src/test/java/com/donation/controller/favorite/FavoriteControllerDocTest.java
  src/test/java/com/donation/controller/favorite/FavoriteControllerTest.java
  src/test/java/com/donation/domain/FavoritesTest.java
  src/test/java/com/donation/repository/favorite/FavoriteRepositoryTest.java
  src/test/java/com/donation/service/favorite/FavoriteServiceTest.java
Labels: 백엔드, 리팩터링

#26 Merge: 유저, 포스트, 좋아요 기능
  build.gradle
  src/docs/asciidoc/index.adoc
  src/main/java/com/donation/common/request/favorites/LikeSaveAndCancelReqDto.java
  src/main/java/com/donation/common/request/post/PostSaveReqDto.java
  src/main/java/com/donation/common/request/post/PostUpdateReqDto.java
  src/main/java/com/donation/common/response/post/PostFindRespDto.java
  src/main/java/com/donation/common/response/post/PostListRespDto.java
  src/main/java/com/donation/common/response/post/PostSaveRespDto.java
  src/main/java/com/donation/common/response/user/UserRespDto.java
  src/main/java/com/donation/config/RedisConfig.java
  src/main/java/com/donation/domain/embed/Write.java
  src/main/java/com/donation/domain/entites/Favorites.java
  src/main/java/com/donation/domain/entites/Post.java
  src/main/java/com/donation/domain/enums/Category.java
  src/main/java/com/donation/repository/favorite/FavoriteRedisRepository.java
  src/main/java/com/donation/repository/favorite/FavoriteRepository.java
  src/main/java/com/donation/repository/post/PostRepository.java
  src/main/java/com/donation/repository/post/PostRepositoryCustom.java
  src/main/java/com/donation/repository/post/PostRepositoryCustomImpl.java
  src/main/java/com/donation/repository/postdetailimage/PostDetailImageRepository.java
  src/main/java/com/donation/repository/user/UserRepository.java
  src/main/java/com/donation/service/donation/DonationService.java
  src/main/java/com/donation/service/favorite/FavoriteService.java
  src/main/java/com/donation/service/post/PostScheduleService.java
  src/main/java/com/donation/service/post/PostService.java
  src/main/java/com/donation/service/user/UserService.java
  src/main/java/com/donation/web/controller/admin/AdminController.java
  src/main/java/com/donation/web/controller/favortie/FavoriteController.java
  src/main/java/com/donation/web/controller/post/PostController.java
  src/main/resources/application-local.yml
  src/main/resources/templates/docs/index.html
  src/test/java/com/donation/common/FavoriteFixtures.java
  src/test/java/com/donation/common/PostFixtures.java
  src/test/java/com/donation/common/TestDtoDataFactory.java
  src/test/java/com/donation/common/TestEntityDataFactory.java
  src/test/java/com/donation/controller/favorite/FavoriteControllerDocTest.java
  src/test/java/com/donation/controller/favorite/FavoriteControllerTest.java
  src/test/java/com/donation/controller/post/PostControllerDocTest.java
  src/test/java/com/donation/controller/post/PostControllerTest.java
  src/test/java/com/donation/domain/FavoritesTest.java
  src/test/java/com/donation/domain/PostTest.java
  src/test/java/com/donation/domain/UserTest.java
  src/test/java/com/donation/repository/favorite/FavoriteRepositoryTest.java
  src/test/java/com/donation/repository/post/PostRepositoryTest.java
  src/test/java/com/donation/service/favorite/FavoriteServiceTest.java
  src/test/java/com/donation/service/post/PostScheduleServiceTest.java
  src/test/java/com/donation/service/post/PostServiceTest.java
  src/test/resources/application.yml
Labels: 백엔드, Merge
