Repository Donation-Project/backend, pull requests merged in 2022-11, with the labels that each got.

#64 feat: 댓글 기능 추가
  .gitignore
  src/docs/asciidoc/index.adoc
  src/main/java/com/donation/common/request/comment/CommentSaveReqDto.java
  src/main/java/com/donation/common/response/comment/CommentResponse.java
  src/main/java/com/donation/common/response/comment/ReplyResponse.java
  src/main/java/com/donation/domain/embed/Message.java
  src/main/java/com/donation/domain/entites/Comment.java
  src/main/java/com/donation/exception/DonationInvalidateException.java
  src/main/java/com/donation/repository/comment/CommentRepository.java
  src/main/java/com/donation/service/comment/CommentService.java
  src/main/java/com/donation/service/post/PostService.java
  src/main/java/com/donation/web/controller/comment/CommentController.java
  src/main/resources/db/migration/V003__Create_comment.sql
  src/main/resources/templates/docs/index.html
  src/test/java/com/donation/common/CommentFixtures.java
  src/test/java/com/donation/common/PostFixtures.java
  src/test/java/com/donation/controller/comment/CommentControllerTest.java
  src/test/java/com/donation/domain/CommentTest.java
  src/test/java/com/donation/domain/embed/MessageTest.java
  src/test/java/com/donation/repository/comment/CommentRepositoryTest.java
  src/test/java/com/donation/service/comment/CommentServiceTest.java
  src/test/java/com/donation/service/donation/DonationServiceTest.java
Labels: 백엔드, feat

#69 merge: 댓글 기능 추가
  .gitignore
  src/docs/asciidoc/index.adoc
  src/main/java/com/donation/common/request/comment/CommentSaveReqDto.java
  src/main/java/com/donation/common/response/comment/CommentResponse.java
  src/main/java/com/donation/common/response/comment/ReplyResponse.java
  src/main/java/com/donation/domain/embed/Message.java
  src/main/java/com/donation/domain/entites/Comment.java
  src/main/java/com/donation/exception/DonationInvalidateException.java
  src/main/java/com/donation/repository/comment/CommentRepository.java
  src/main/java/com/donation/service/comment/CommentService.java
  src/main/java/com/donation/service/post/PostService.java
  src/main/java/com/donation/web/controller/comment/CommentController.java
  src/main/resources/db/migration/V003__Create_comment.sql
  src/main/resources/templates/docs/index.html
  src/test/java/com/donation/common/CommentFixtures.java
  src/test/java/com/donation/common/PostFixtures.java
  src/test/java/com/donation/controller/comment/CommentControllerTest.java
  src/test/java/com/donation/domain/CommentTest.java
  src/test/java/com/donation/domain/embed/MessageTest.java
  src/test/java/com/donation/repository/comment/CommentRepositoryTest.java
  src/test/java/com/donation/service/comment/CommentServiceTest.java
  src/test/java/com/donation/service/donation/DonationServiceTest.java
Labels: 백엔드, Merge

#71 feat: 현재 모금액을 저장하는 currentAmount 필드 추가 및 동시성 문제 해결
  src/docs/asciidoc/index.adoc
  src/main/java/com/donation/common/request/donation/DonationSaveReqDto.java
  src/main/java/com/donation/common/response/post/PostFindRespDto.java
  src/main/java/com/donation/common/response/post/PostListRespDto.java
  src/main/java/com/donation/domain/entites/Donation.java
  src/main/java/com/donation/domain/entites/Post.java
  src/main/java/com/donation/repository/post/PostRepository.java
  src/main/java/com/donation/repository/post/PostRepositoryCustomImpl.java
  src/main/java/com/donation/service/donation/DonationService.java
  src/main/java/com/donation/service/post/PostService.java
  src/main/java/com/donation/web/controller/donation/DonationController.java
  src/main/resources/application-local.yml
  src/main/resources/db/migration/V004__Add_post_currentAmount.sql
  src/main/resources/templates/docs/index.html
  src/test/java/com/donation/common/DonationFixtures.java
  src/test/java/com/donation/common/PostFixtures.java
  src/test/java/com/donation/common/TestEntityDataFactory.java
  src/test/java/com/donation/controller/admin/AdminControllerDocTest.java
  src/test/java/com/donation/controller/admin/AdminControllerTest.java
  src/test/java/com/donation/controller/donation/DonationControllerDocTest.java
  src/test/java/com/donation/controller/donation/DonationControllerTest.java
  src/test/java/com/donation/controller/post/PostControllerTest.java
  src/test/java/com/donation/domain/PostTest.java
  src/test/java/com/donation/repository/favorite/FavoriteRepositoryTest.java
  src/test/java/com/donation/repository/post/PostRepositoryTest.java
  src/test/java/com/donation/service/donation/DonationServiceTest.java
  src/test/java/com/donation/service/favorite/FavoriteServiceTest.java
  src/test/java/com/donation/service/post/PostServiceTest.java
  src/test/resources/application.yml
Labels: 백엔드, feat

#72 Merge: 현재 모금액을 저장하는 currentAmount 필드 추가
  src/docs/asciidoc/index.adoc
  src/main/java/com/donation/common/request/donation/DonationSaveReqDto.java
  src/main/java/com/donation/common/response/post/PostFindRespDto.java
  src/main/java/com/donation/common/response/post/PostListRespDto.java
  src/main/java/com/donation/domain/entites/Donation.java
  src/main/java/com/donation/domain/entites/Post.java
  src/main/java/com/donation/repository/post/PostRepository.java
  src/main/java/com/donation/repository/post/PostRepositoryCustomImpl.java
  src/main/java/com/donation/service/donation/DonationService.java
  src/main/java/com/donation/service/post/PostService.java
  src/main/java/com/donation/web/controller/donation/DonationController.java
  src/main/resources/application-local.yml
  src/main/resources/db/migration/V004__Add_post_currentAmount.sql
  src/main/resources/templates/docs/index.html
  src/test/java/com/donation/common/DonationFixtures.java
  src/test/java/com/donation/common/PostFixtures.java
  src/test/java/com/donation/common/TestEntityDataFactory.java
  src/test/java/com/donation/controller/admin/AdminControllerDocTest.java
  src/test/java/com/donation/controller/admin/AdminControllerTest.java
  src/test/java/com/donation/controller/donation/DonationControllerDocTest.java
  src/test/java/com/donation/controller/donation/DonationControllerTest.java
  src/test/java/com/donation/controller/post/PostControllerTest.java
  src/test/java/com/donation/domain/PostTest.java
  src/test/java/com/donation/repository/favorite/FavoriteRepositoryTest.java
  src/test/java/com/donation/repository/post/PostRepositoryTest.java
  src/test/java/com/donation/service/donation/DonationServiceTest.java
  src/test/java/com/donation/service/favorite/FavoriteServiceTest.java
  src/test/java/com/donation/service/post/PostServiceTest.java
  src/test/resources/application.yml
Labels: 백엔드, Merge

#78 feat: 유저 삭제시 외래키 참조에 의해 삭제가 안되는 버그 수정
  .gitignore
  build.gradle
  src/docs/asciidoc/index.adoc
  src/main/java/com/donation/service/user/UserService.java
  src/main/java/com/donation/web/controller/user/UserController.java
  src/main/resources/templates/docs/api/Admin-API.html
  src/main/resources/templates/docs/api/Comment-API.html
  src/main/resources/templates/docs/api/Donation-API.html
  src/main/resources/templates/docs/api/Favorite-API.html
  src/main/resources/templates/docs/api/Post-API.html
  src/main/resources/templates/docs/api/User-API.html
  src/main/resources/templates/docs/index.html
  src/test/java/com/donation/controller/user/UserControllerTest.java
  src/test/java/com/donation/service/user/UserServiceTest.java
Labels: 백엔드, feat

#84 feat: JWT를 이용한 회원검증 기능 추가
  src/docs/asciidoc/api/Auth-API.adoc
  src/docs/asciidoc/api/User-API.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/donation/auth/LoginInfo.java
  src/main/java/com/donation/auth/LoginInfoArgumentResolver.java
  src/main/java/com/donation/auth/LoginInfoExtractor.java
  src/main/java/com/donation/auth/LoginMember.java
  src/main/java/com/donation/common/request/auth/TokenRenewalRequest.java
  src/main/java/com/donation/common/request/user/UserLoginReqDto.java
  src/main/java/com/donation/common/response/auth/AccessAndRefreshTokenResponse.java
  src/main/java/com/donation/common/response/auth/AccessTokenResponse.java
  src/main/java/com/donation/config/WebMvcConfig.java
  src/main/java/com/donation/config/auth/token/TokenProvider.java
  src/main/java/com/donation/config/auth/token/TokenProviderService.java
  src/main/java/com/donation/service/auth/application/AuthService.java
  src/main/java/com/donation/service/auth/application/AuthTokenCreator.java
  src/main/java/com/donation/service/auth/application/JwtTokenProvider.java
  src/main/java/com/donation/service/auth/application/TokenCreator.java
  src/main/java/com/donation/service/auth/application/TokenProvider.java
  src/main/java/com/donation/service/auth/domain/AuthToken.java
  src/main/java/com/donation/service/auth/repository/InMemoryTokenRepository.java
  src/main/java/com/donation/service/auth/repository/TokenRepository.java
  src/main/java/com/donation/web/controller/auth/AuthController.java
  src/main/java/com/donation/web/controller/post/PostController.java
  src/main/java/com/donation/web/controller/user/UserController.java
  src/main/resources/application-jwt.yml
  src/main/resources/application.yml
  src/main/resources/db/migration/V005__Alter_user.sql
  src/main/resources/templates/docs/index.html
  src/test/java/com/donation/common/AuthFixtures.java
  src/test/java/com/donation/common/UserFixtures.java
  src/test/java/com/donation/controller/auth/AuthControllerTest.java
  src/test/java/com/donation/controller/comment/CommentControllerTest.java
  src/test/java/com/donation/controller/favorite/FavoriteControllerTest.java
  src/test/java/com/donation/controller/post/PostControllerTest.java
  src/test/java/com/donation/controller/user/UserControllerTest.java
  src/test/java/com/donation/domain/AuthTokenTest.java
  src/test/java/com/donation/repository/auth/InMemoryTokenRepositoryTest.java
  src/test/java/com/donation/service/auth/AuthServiceTest.java
  src/test/java/com/donation/service/auth/TokenCreatorTest.java
  src/test/java/com/donation/service/auth/TokenProviderTest.java
  src/test/java/com/donation/service/user/AuthServiceTest.java
  src/test/resources/application.yml
Labels: 백엔드, feat

#86 refactor: Auth 로직 추가로 인한 User Controller 코드 수정
  src/docs/asciidoc/api/User-API.adoc
  src/main/java/com/donation/common/request/post/PostSaveReqDto.java
  src/main/java/com/donation/common/request/post/PostUpdateReqDto.java
  src/main/java/com/donation/common/request/user/UserLoginReqDto.java
  src/main/java/com/donation/service/user/UserService.java
  src/main/java/com/donation/web/controller/user/UserController.java
  src/main/resources/templates/docs/index.html
  src/test/java/com/donation/common/AuthFixtures.java
  src/test/java/com/donation/common/UserFixtures.java
  src/test/java/com/donation/controller/user/UserControllerTest.java
  src/test/java/com/donation/service/auth/AuthServiceTest.java
  src/test/java/com/donation/service/user/UserServiceTest.java
Labels: 백엔드, 리팩터링, fix

#87 refactor: Auth 로직 추가로 인한 Post 코드 수정
  src/docs/asciidoc/api/Post-API.adoc
  src/main/java/com/donation/auth/LoginMember.java
  src/main/java/com/donation/domain/entites/Post.java
  src/main/java/com/donation/service/post/PostService.java
  src/main/java/com/donation/web/controller/post/PostController.java
  src/test/java/com/donation/controller/post/PostControllerTest.java
  src/test/java/com/donation/domain/PostTest.java
  src/test/java/com/donation/service/post/PostServiceTest.java
Labels: 백엔드, 리팩터링

#91 refactor: Auth 로직 추가로 인한 Comment 코드 수정
  src/docs/asciidoc/api/comment.adoc
  src/main/java/com/donation/service/comment/CommentService.java
  src/main/java/com/donation/web/controller/comment/CommentController.java
  src/main/resources/templates/docs/index.html
  src/test/java/com/donation/controller/comment/CommentControllerTest.java
  src/test/java/com/donation/service/comment/CommentServiceTest.java
Labels: 백엔드, 리팩터링

#93 hoxfix: 운영서버에서 API 문서를 못불러오는 현상 (임시 수정)
  src/docs/asciidoc/index.adoc
  src/main/resources/templates/docs/index.html
Labels: 백엔드, Merge, fix

#94 hoxfix: API문서에 접근 못하는 오류 수정
  src/main/java/com/donation/config/WebMvcConfig.java
  src/main/resources/templates/docs/index.html
Labels: 백엔드, fix

#97 feat: User 도메인의 기능 확장
  build.gradle
  src/docs/asciidoc/api/user.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/donation/common/request/user/UserEmailReqDto.java
  src/main/java/com/donation/common/request/user/UserPasswordModifyReqDto.java
  src/main/java/com/donation/common/response/user/UserEmailRespDto.java
  src/main/java/com/donation/service/user/UserService.java
  src/main/java/com/donation/web/controller/user/UserController.java
  src/main/resources/templates/docs/index.html
  src/test/java/com/donation/common/UserFixtures.java
  src/test/java/com/donation/controller/user/UserControllerTest.java
  src/test/java/com/donation/service/user/UserServiceTest.java
Labels: 백엔드, feat

#98 feat: Bcrypt 패스워드 관련 코드 빈으로 등록
  src/main/java/com/donation/infrastructure/PasswordEncoder.java
  src/main/java/com/donation/service/auth/application/AuthService.java
  src/main/java/com/donation/service/user/UserService.java
  src/main/resources/templates/docs/index.html
  src/test/java/com/donation/infrastructure/PasswordEncoderTest.java
Labels: 백엔드, 리팩터링, feat

#103 refactor : 프로그램 전체 리팩토링 Donation
  build.gradle
  src/docs/asciidoc/api/user.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/donation/common/request/donation/DonationFilterReqDto.java
  src/main/java/com/donation/common/request/donation/DonationSaveReqDto.java
  src/main/java/com/donation/common/request/user/UserEmailReqDto.java
  src/main/java/com/donation/common/request/user/UserPasswordModifyReqDto.java
  src/main/java/com/donation/common/response/donation/DonationFindByFilterRespDto.java
  src/main/java/com/donation/common/response/donation/DonationFindRespDto.java
  src/main/java/com/donation/common/response/user/UserEmailRespDto.java
  src/main/java/com/donation/infrastructure/PasswordEncoder.java
  src/main/java/com/donation/repository/donation/DonationRepository.java
  src/main/java/com/donation/repository/donation/DonationRepositoryCustom.java
  src/main/java/com/donation/repository/donation/DonationRepositoryCustomImpl.java
  src/main/java/com/donation/service/auth/application/AuthService.java
  src/main/java/com/donation/service/donation/DonationService.java
  src/main/java/com/donation/service/user/UserService.java
  src/main/java/com/donation/web/controller/donation/DonationController.java
  src/main/java/com/donation/web/controller/user/UserController.java
  src/main/resources/templates/docs/index.html
  src/test/java/com/donation/common/DonationFixtures.java
  src/test/java/com/donation/common/UserFixtures.java
  src/test/java/com/donation/controller/donation/DonationControllerDocTest.java
  src/test/java/com/donation/controller/donation/DonationControllerTest.java
  src/test/java/com/donation/controller/user/UserControllerTest.java
  src/test/java/com/donation/infrastructure/PasswordEncoderTest.java
  src/test/java/com/donation/repository/donation/DonationRepositoryTest.java
  src/test/java/com/donation/service/donation/DonationServiceTest.java
  src/test/java/com/donation/service/user/UserServiceTest.java
Labels: 백엔드, 리팩터링

#107 refactor : 프로그램 전체 리팩토링 Donation
  src/main/java/com/donation/domain/donation/dto/DonationFindByFilterRespDto.java
  src/main/java/com/donation/domain/donation/dto/DonationFindRespDto.java
  src/main/java/com/donation/domain/donation/dto/DonationSaveReqDto.java
  src/main/java/com/donation/domain/donation/entity/Donation.java
  src/main/java/com/donation/domain/donation/service/DonationService.java
  src/main/java/com/donation/presentation/DonationController.java
  src/test/java/com/donation/common/DonationFixtures.java
  src/test/java/com/donation/domain/donation/application/DonationServiceTest.java
  src/test/java/com/donation/domain/donation/entity/DonationTest.java
  src/test/java/com/donation/presentation/AdminControllerDocTest.java
  src/test/java/com/donation/presentation/AdminControllerTest.java
  src/test/java/com/donation/presentation/DonationControllerTest.java
Labels: 백엔드, 리팩터링

#109 hotfix: Donation, Admin 테스트 코드 실패 수정
  src/docs/asciidoc/api/admin.adoc
  src/docs/asciidoc/api/donation.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/donation/domain/donation/dto/DonationFilterReqDto.java
  src/main/java/com/donation/domain/donation/repository/DonationRepositoryCustomImpl.java
  src/main/java/com/donation/presentation/AdminController.java
  src/main/resources/templates/docs/index.html
  src/test/java/com/donation/common/DonationFixtures.java
  src/test/java/com/donation/presentation/AdminControllerTest.java
  src/test/java/com/donation/presentation/DonationControllerTest.java
Labels: bug, 백엔드, fix

#110 merge: Donation 리팩토링 및 Review 기능 추가
  src/docs/asciidoc/api/admin.adoc
  src/docs/asciidoc/api/donation.adoc
  src/docs/asciidoc/api/review.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/donation/domain/donation/dto/DonationFilterReqDto.java
  src/main/java/com/donation/domain/donation/dto/DonationFindByFilterRespDto.java
  src/main/java/com/donation/domain/donation/dto/DonationFindRespDto.java
  src/main/java/com/donation/domain/donation/dto/DonationSaveReqDto.java
  src/main/java/com/donation/domain/donation/entity/Donation.java
  src/main/java/com/donation/domain/donation/repository/DonationRepositoryCustomImpl.java
  src/main/java/com/donation/domain/donation/service/DonationService.java
  src/main/java/com/donation/domain/reviews/application/ReviewService.java
  src/main/java/com/donation/domain/reviews/dto/ReviewReqDto.java
  src/main/java/com/donation/domain/reviews/dto/ReviewRespDto.java
  src/main/java/com/donation/domain/reviews/entity/Reviews.java
  src/main/java/com/donation/domain/reviews/repository/ReviewRepository.java
  src/main/java/com/donation/infrastructure/embed/Write.java
  src/main/java/com/donation/presentation/AdminController.java
  src/main/java/com/donation/presentation/DonationController.java
  src/main/java/com/donation/presentation/ReviewController.java
  src/main/resources/templates/docs/index.html
  src/test/java/com/donation/common/DonationFixtures.java
  src/test/java/com/donation/common/ReviewFixture.java
  src/test/java/com/donation/domain/donation/application/DonationServiceTest.java
  src/test/java/com/donation/domain/donation/entity/DonationTest.java
  src/test/java/com/donation/domain/reviews/application/ReviewServiceTest.java
  src/test/java/com/donation/domain/reviews/entity/ReviewsTest.java
  src/test/java/com/donation/domain/reviews/repository/ReviewRepositoryTest.java
  src/test/java/com/donation/infrastructure/embed/WriteTest.java
  src/test/java/com/donation/presentation/AdminControllerDocTest.java
  src/test/java/com/donation/presentation/AdminControllerTest.java
  src/test/java/com/donation/presentation/DonationControllerTest.java
  src/test/java/com/donation/presentation/ReviewControllerTest.java
Labels: 백엔드, Merge

#114 feat: 유저, 게시물 데이터 100만개 삽입
  .github/workflows/backend-dev.yml
  .github/workflows/backend-prod.yml
  .github/workflows/test-pull-request.yml
  Dockerfile.dev
  build.gradle
  src/main/java/com/donation/domain/post/repository/PostJdbcRepository.java
  src/main/resources/application.yml
  src/main/resources/templates/docs/index.html
  src/test/java/com/donation/common/PostFixtures.java
  src/test/java/com/donation/common/UserFixtures.java
  src/test/java/com/donation/domain/post/repository/PostBulkInsert.java
Labels: 💻백엔드, ⚡기능

#115 merge: 코드 분석 테스트 및 코드 최신화
  .github/workflows/test-pull-request.yml
  src/test/java/com/donation/domain/post/repository/PostBulkInsert.java
Labels: 💻백엔드

#116 refactor : 프로그램 전체 리팩토링 Donation
  src/docs/asciidoc/api/donation.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/donation/domain/donation/dto/DonationSaveReqDto.java
  src/main/java/com/donation/domain/donation/entity/Donation.java
  src/main/java/com/donation/domain/donation/service/DonationService.java
  src/main/java/com/donation/domain/user/entity/User.java
  src/main/java/com/donation/presentation/DonationController.java
  src/test/java/com/donation/common/DonationFixtures.java
  src/test/java/com/donation/common/UserFixtures.java
  src/test/java/com/donation/domain/donation/application/DonationServiceTest.java
  src/test/java/com/donation/domain/donation/entity/DonationTest.java
  src/test/java/com/donation/presentation/DonationControllerTest.java
Labels: 💻백엔드, 🛠리팩터링

#119 feat: LOGBack 구현
  src/main/java/com/donation/global/aspect/LoggingAspect.java
  src/main/resources/logback-spring.xml
  src/test/java/com/donation/domain/comment/repository/CommentRepositoryTest.java
Labels: 💻백엔드, ⚡기능

#120 merge: dev 정보 최신화
  .github/workflows/test-pull-request.yml
  src/docs/asciidoc/api/donation.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/donation/domain/donation/dto/DonationSaveReqDto.java
  src/main/java/com/donation/domain/donation/entity/Donation.java
  src/main/java/com/donation/domain/donation/service/DonationService.java
  src/main/java/com/donation/domain/user/entity/User.java
  src/main/java/com/donation/presentation/DonationController.java
  src/test/java/com/donation/common/DonationFixtures.java
  src/test/java/com/donation/common/UserFixtures.java
  src/test/java/com/donation/domain/donation/application/DonationServiceTest.java
  src/test/java/com/donation/domain/donation/entity/DonationTest.java
  src/test/java/com/donation/presentation/DonationControllerTest.java
Labels: 💻백엔드, Merge

#121 feat: 깃액션 테스트 결과 출력
  .github/workflows/test-pull-request.yml
  src/main/resources/templates/docs/index.html
Labels: 💻백엔드, ✔버그수정

#123 feat: prometheus 설정 추가
  .github/workflows/test-pull-request.yml
  build.gradle
Labels: 💻백엔드, ⚡기능

#125 feat: 기존 Post 페이징 방식 -> 커서 기반 페이징으로 변경
  build.gradle
  src/main/java/com/donation/domain/auth/application/AuthService.java
  src/main/java/com/donation/domain/favorite/repository/FavoriteRepository.java
  src/main/java/com/donation/domain/post/dto/PostListRespDto.java
  src/main/java/com/donation/domain/post/repository/PostJdbcRepository.java
  src/main/java/com/donation/domain/post/repository/PostRepository.java
  src/main/java/com/donation/domain/post/repository/PostRepositoryCustom.java
  src/main/java/com/donation/domain/post/repository/PostRepositoryCustomImpl.java
  src/main/java/com/donation/domain/post/service/PostService.java
  src/main/java/com/donation/domain/user/repository/UserRepository.java
  src/main/java/com/donation/domain/user/service/UserService.java
  src/main/java/com/donation/global/DonationAdvice.java
  src/main/java/com/donation/infrastructure/common/CommonResponse.java
  src/main/java/com/donation/infrastructure/common/ErrorResponse.java
  src/main/java/com/donation/infrastructure/support/PasswordEncoder.java
  src/main/java/com/donation/infrastructure/util/CursorRequest.java
  src/main/java/com/donation/infrastructure/util/PageCursor.java
  src/main/java/com/donation/infrastructure/util/PageCustom.java
  src/main/java/com/donation/infrastructure/util/PageData.java
  src/main/java/com/donation/infrastructure/util/PagingUtils.java
  src/main/java/com/donation/presentation/AdminController.java
  src/main/java/com/donation/presentation/PostController.java
  src/main/java/com/donation/presentation/UserController.java
  src/main/resources/templates/docs/index.html
  src/test/java/com/donation/common/PostFixtures.java
  src/test/java/com/donation/common/utils/CursorRequestFixtures.java
  src/test/java/com/donation/domain/post/application/PostServiceTest.java
  src/test/java/com/donation/domain/user/application/UserServiceTest.java
  src/test/java/com/donation/domain/user/repository/UserRepositoryTest.java
  src/test/java/com/donation/infrastructure/support/PasswordEncoderTest.java
  src/test/java/com/donation/infrastructure/util/CursorRequestTest.java
  src/test/java/com/donation/infrastructure/util/PageDataTest.java
  src/test/java/com/donation/presentation/AdminControllerTest.java
  src/test/java/com/donation/presentation/PostControllerTest.java
  src/test/java/com/donation/presentation/UserControllerTest.java
Labels: 💻백엔드, 🛠리팩터링, ⚡기능

#129 feat: 회원가입시 이메일 인증코드 검증 로직
  .github/workflows/backend-dev.yml
  .github/workflows/backend-prod.yml
  .github/workflows/test-pull-request.yml
  .gitignore
  build.gradle
  src/docs/asciidoc/api/user.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/donation/domain/auth/application/AuthCodeService.java
  src/main/java/com/donation/domain/auth/application/AuthService.java
  src/main/java/com/donation/domain/auth/application/mail/MailSender.java
  src/main/java/com/donation/domain/auth/application/mail/MailSenderImpl.java
  src/main/java/com/donation/domain/auth/application/mail/MailService.java
  src/main/java/com/donation/domain/auth/application/mail/dto/MailReqDto.java
  src/main/java/com/donation/domain/auth/dto/VerificationReqDto.java
  src/main/java/com/donation/domain/auth/entity/AuthCode.java
  src/main/java/com/donation/domain/auth/repository/AuthCodeRepository.java
  src/main/java/com/donation/domain/donation/application/DonationService.java
  src/main/java/com/donation/domain/post/application/Image/ByteImageCreator.java
  src/main/java/com/donation/domain/post/application/Image/ImageCreator.java
  src/main/java/com/donation/domain/post/application/Image/ImageService.java
  src/main/java/com/donation/domain/post/application/PostScheduleService.java
  src/main/java/com/donation/domain/post/application/PostService.java
  src/main/java/com/donation/domain/user/application/UserService.java
  src/main/java/com/donation/infrastructure/support/AuthCodeGenerator.java
  src/main/java/com/donation/infrastructure/support/AuthEncoder.java
  src/main/java/com/donation/infrastructure/support/PasswordEncoder.java
  src/main/java/com/donation/presentation/AdminController.java
  src/main/java/com/donation/presentation/DonationController.java
  src/main/java/com/donation/presentation/PostController.java
  src/main/java/com/donation/presentation/UserController.java
  src/main/resources/application.yml
  src/main/resources/db/migration/V006__CREATE_authcode.sql
  src/main/resources/templates/docs/index.html
  src/test/java/com/donation/common/AuthFixtures.java
  src/test/java/com/donation/domain/auth/application/AuthCodeServiceTest.java
  src/test/java/com/donation/domain/auth/application/AuthServiceTest.java
  src/test/java/com/donation/domain/auth/entity/AuthCodeTest.java
  src/test/java/com/donation/domain/auth/repository/AuthCodeRepositoryTest.java
  src/test/java/com/donation/domain/donation/application/DonationServiceTest.java
  src/test/java/com/donation/domain/post/application/PostScheduleServiceTest.java
  src/test/java/com/donation/domain/post/application/PostServiceTest.java
  src/test/java/com/donation/domain/post/application/image/ImageServiceTest.java
  src/test/java/com/donation/domain/user/application/UserServiceTest.java
  src/test/java/com/donation/infrastructure/support/PasswordEncoderTest.java
  src/test/java/com/donation/presentation/AdminControllerTest.java
  src/test/java/com/donation/presentation/DonationControllerTest.java
  src/test/java/com/donation/presentation/PostControllerTest.java
  src/test/java/com/donation/presentation/UserControllerTest.java
  src/test/resources/application.yml
Labels: 💻백엔드, ⚡기능

#134 feat: 이벤트 기반 알림 기능 추가
  src/main/java/com/donation/domain/comment/application/CommentService.java
  src/main/java/com/donation/domain/comment/event/NewCommentNotificationEvent.java
  src/main/java/com/donation/domain/comment/event/NewReplyNotificationEvent.java
  src/main/java/com/donation/domain/donation/application/DonationService.java
  src/main/java/com/donation/domain/donation/event/DonateNotificationEvent.java
  src/main/java/com/donation/domain/favorite/application/FavoriteService.java
  src/main/java/com/donation/domain/favorite/event/PostLikeNotificationEvent.java
  src/main/java/com/donation/domain/notification/application/NotificationService.java
  src/main/java/com/donation/domain/notification/entity/Notification.java
  src/main/java/com/donation/domain/notification/entity/NotificationMessage.java
  src/main/java/com/donation/domain/notification/entity/NotifyType.java
  src/main/java/com/donation/domain/notification/handler/NotificationEventHandler.java
  src/main/java/com/donation/domain/notification/repository/NotificationRepository.java
  src/main/java/com/donation/domain/post/application/PostService.java
  src/main/java/com/donation/domain/post/event/NewPostNotificationEvent.java
  src/main/resources/templates/docs/index.html
  src/test/java/com/donation/common/UserFixtures.java
  src/test/java/com/donation/domain/favorite/application/FavoriteServiceTest.java
  src/test/java/com/donation/domain/notification/application/NotificationServiceTest.java
  src/test/java/com/donation/domain/notification/entity/NotificationTest.java
  src/test/java/com/donation/domain/notification/handler/NotificationEventHandlerTest.java
  src/test/java/com/donation/domain/notification/repository/NotificationRepositoryTest.java
  src/test/java/com/donation/presentation/NotificationControllerTest.java
Labels: 💻백엔드, ⚡기능
